platform :ios, ‘9.0’

target 'TSUMUtilMaster' do

use_frameworks!

#pod 'UMCCommon'

#pod 'UMCSecurityPlugins'

#pod 'UMCShare/UI'

#pod 'UMCShare/Social/WeChat'

#pod 'UMCShare/Social/QQ'

#pod 'MJExtension'
end
